[package]
name = "ex_em_ell"
version = "0.1.0"
edition = "2021"
description = "Provide macros for serializing and deserializing XML"

license = "MIT OR Apache-2.0"

[dependencies]
ex_em_ell_derive = { path = "../ex_em_ell_derive", version = "0.1.0", optional = true }
thiserror = "1.0.50"
xml-rs = "0.8.16"

[features]
default = ["derive"]
derive = ["ex_em_ell_derive"]

[dev-dependencies]
insta = { version = "1.34.0", features = [ "glob" ] }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[package.metadata.cyclonedx]
format = "json"
included_dependencies = "all"
output_options = { cdx = true, pattern = "package" }
