name: "Release to crates.io"

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "release type (major, minor, patch)"
        required: true
        default: "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v3

      # Build and test before releasing
      - name: Build the default flake output
        run: nix build

      - name: Check the flake outputs
        run: nix flake check

      # Run cargo-release
      - name: Release the crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: nix develop --command cargo release --execute "${{ github.event.inputs.releaseType }}"
